package main

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/buildpacks/imgutil/remote"
	"github.com/google/go-containerregistry/pkg/authn"
	"github.com/pkg/errors"

	"github.com/buildpacks/lifecycle"
	"github.com/buildpacks/lifecycle/buildpack"
	"github.com/buildpacks/lifecycle/cache"
	"github.com/buildpacks/lifecycle/cmd"
	"github.com/buildpacks/lifecycle/cmd/lifecycle/cli"
	"github.com/buildpacks/lifecycle/platform"
	"github.com/buildpacks/lifecycle/platform/config"
	"github.com/buildpacks/lifecycle/platform/exit"
)

func main() {
	p, err := platform.New(cmd.DefaultLogger)
	if err != nil {
		cmd.Exit(err)
	}
	phase := strings.TrimSuffix(filepath.Base(os.Args[0]), filepath.Ext(os.Args[0]))
	switch phase {
	case "detector":
		cli.Run(&detectCmd{Platform: p}, false)
	case "analyzer":
		cli.Run(&analyzeCmd{Platform: p}, false)
	case "restorer":
		cli.Run(&restoreCmd{Platform: p}, false)
	case "builder":
		cli.Run(&buildCmd{Platform: p}, false)
	case "exporter":
		cli.Run(&exportCmd{Platform: p}, false)
	case "creator":
		cli.Run(&createCmd{Platform: p}, false)
	case "extender":
		cli.Run(&extendCmd{Platform: p}, false)
	case "rebaser":
		cli.Run(&rebaseCmd{Platform: p}, false)
	default:
		if len(os.Args) < 2 {
			cmd.Exit(exit.ErrorFromCode(exit.CodeForInvalidArgs, "parse arguments"))
		}
		if os.Args[1] == "-version" {
			cmd.ExitWithVersion()
		}
		subcommand(p)
	}
}

func subcommand(p *platform.Platform) {
	phase := filepath.Base(os.Args[1])
	switch phase {
	case "detect":
		cli.Run(&detectCmd{Platform: p}, true)
	case "analyze":
		cli.Run(&analyzeCmd{Platform: p}, true)
	case "restore":
		cli.Run(&restoreCmd{Platform: p}, true)
	case "build":
		cli.Run(&buildCmd{Platform: p}, true)
	case "export":
		cli.Run(&exportCmd{Platform: p}, true)
	case "rebase":
		cli.Run(&rebaseCmd{Platform: p}, true)
	case "create":
		cli.Run(&createCmd{Platform: p}, true)
	case "extend":
		cli.Run(&extendCmd{Platform: p}, true)
	default:
		cmd.Exit(exit.ErrorFromCode(exit.CodeForInvalidArgs, "unknown phase:", phase))
	}
}

// handlers

type DefaultCacheHandler struct {
	keychain authn.Keychain
}

func NewCacheHandler(keychain authn.Keychain) *DefaultCacheHandler {
	return &DefaultCacheHandler{
		keychain: keychain,
	}
}

func (ch *DefaultCacheHandler) InitCache(cacheImageRef string, cacheDir string) (lifecycle.Cache, error) {
	var (
		cacheStore lifecycle.Cache
		err        error
	)
	if cacheImageRef != "" {
		cacheStore, err = cache.NewImageCacheFromName(cacheImageRef, ch.keychain, cmd.DefaultLogger)
		if err != nil {
			return nil, errors.Wrap(err, "creating image cache")
		}
	} else if cacheDir != "" {
		cacheStore, err = cache.NewVolumeCache(cacheDir)
		if err != nil {
			return nil, errors.Wrap(err, "creating volume cache")
		}
	}
	return cacheStore, nil
}

type DefaultRegistryHandler struct {
	keychain authn.Keychain
}

func NewRegistryHandler(keychain authn.Keychain) *DefaultRegistryHandler {
	return &DefaultRegistryHandler{
		keychain: keychain,
	}
}

func (rv *DefaultRegistryHandler) EnsureReadAccess(imageRefs ...string) error {
	for _, imageRef := range imageRefs {
		if err := verifyReadAccess(imageRef, rv.keychain); err != nil {
			return err
		}
	}
	return nil
}

func (rv *DefaultRegistryHandler) EnsureWriteAccess(imageRefs ...string) error {
	for _, imageRef := range imageRefs {
		if err := verifyReadWriteAccess(imageRef, rv.keychain); err != nil {
			return err
		}
	}
	return nil
}

func verifyReadAccess(imageRef string, keychain authn.Keychain) error {
	if imageRef == "" {
		return nil
	}
	img, _ := remote.NewImage(imageRef, keychain)
	if !img.CheckReadAccess() {
		return errors.Errorf("ensure registry read access to %s", imageRef)
	}
	return nil
}

func verifyReadWriteAccess(imageRef string, keychain authn.Keychain) error {
	if imageRef == "" {
		return nil
	}
	img, _ := remote.NewImage(imageRef, keychain)
	if !img.CheckReadWriteAccess() {
		return errors.Errorf("ensure registry read/write access to %s", imageRef)
	}
	return nil
}

// helpers

func initCache(cacheImageTag, cacheDir string, keychain authn.Keychain) (lifecycle.Cache, error) {
	var (
		cacheStore lifecycle.Cache
		err        error
	)
	if cacheImageTag != "" {
		cacheStore, err = cache.NewImageCacheFromName(cacheImageTag, keychain, cmd.DefaultLogger)
		if err != nil {
			return nil, exit.ErrorFromErr(err, "create image cache")
		}
	} else if cacheDir != "" {
		cacheStore, err = cache.NewVolumeCache(cacheDir)
		if err != nil {
			return nil, exit.ErrorFromErr(err, "create volume cache")
		}
	}
	return cacheStore, nil
}

func verifyBuildpackApis(group buildpack.Group) error {
	for _, bp := range group.Group {
		if bp.API == "" {
			// if this group was generated by this lifecycle bp.API should be set
			// but if for some reason it isn't default to 0.2
			bp.API = "0.2"
		}
		if err := config.VerifyBuildpackAPI(buildpack.KindBuildpack, bp.String(), bp.API, cmd.DefaultLogger); err != nil { // FIXME: when exporter is extensions-aware, this function call should be modified to provide the right module kind
			return err
		}
	}
	return nil
}
