ignore:
  - vulnerability: CVE-2015-5237 # false positive, see https://github.com/anchore/grype/issues/558
  - vulnerability: CVE-2021-22570 # false positive, see https://github.com/anchore/grype/issues/558
  - vulnerability: GHSA-4v98-7qmw-rqr8 # non-impactful as the lifecycle doesn't invoke BuildKit frontends
  - vulnerability: GHSA-9p26-698r-w4hx # non-impactful as the lifecycle doesn't invoke BuildKit frontends
  - vulnerability: GHSA-m3r6-h7wv-7xxv # non-impactful as the lifecycle doesn't invoke BuildKit frontends
  - vulnerability: GHSA-wr6v-9f75-vh2g # non-impactful as the lifecycle doesn't invoke BuildKit frontends
