// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/buildpacks/lifecycle/buildpack (interfaces: BuildModule)

// Package testmock is a generated GoMock package.
package testmock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	buildpack "github.com/buildpacks/lifecycle/buildpack"
)

// MockBuildModule is a mock of BuildModule interface.
type MockBuildModule struct {
	ctrl     *gomock.Controller
	recorder *MockBuildModuleMockRecorder
}

// MockBuildModuleMockRecorder is the mock recorder for MockBuildModule.
type MockBuildModuleMockRecorder struct {
	mock *MockBuildModule
}

// NewMockBuildModule creates a new mock instance.
func NewMockBuildModule(ctrl *gomock.Controller) *MockBuildModule {
	mock := &MockBuildModule{ctrl: ctrl}
	mock.recorder = &MockBuildModuleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildModule) EXPECT() *MockBuildModuleMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockBuildModule) Build(arg0 buildpack.Plan, arg1 buildpack.BuildConfig, arg2 buildpack.BuildEnv) (buildpack.BuildResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", arg0, arg1, arg2)
	ret0, _ := ret[0].(buildpack.BuildResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MockBuildModuleMockRecorder) Build(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockBuildModule)(nil).Build), arg0, arg1, arg2)
}

// ConfigFile mocks base method.
func (m *MockBuildModule) ConfigFile() *buildpack.Descriptor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigFile")
	ret0, _ := ret[0].(*buildpack.Descriptor)
	return ret0
}

// ConfigFile indicates an expected call of ConfigFile.
func (mr *MockBuildModuleMockRecorder) ConfigFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigFile", reflect.TypeOf((*MockBuildModule)(nil).ConfigFile))
}

// Detect mocks base method.
func (m *MockBuildModule) Detect(arg0 *buildpack.DetectConfig, arg1 buildpack.BuildEnv) buildpack.DetectRun {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detect", arg0, arg1)
	ret0, _ := ret[0].(buildpack.DetectRun)
	return ret0
}

// Detect indicates an expected call of Detect.
func (mr *MockBuildModuleMockRecorder) Detect(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detect", reflect.TypeOf((*MockBuildModule)(nil).Detect), arg0, arg1)
}
