// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/buildpacks/lifecycle/cache (interfaces: ImageDeleter)

// Package testmock is a generated GoMock package.
package testmock

import (
	reflect "reflect"

	imgutil "github.com/buildpacks/imgutil"
	gomock "github.com/golang/mock/gomock"
)

// MockImageDeleter is a mock of ImageDeleter interface.
type MockImageDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockImageDeleterMockRecorder
}

// MockImageDeleterMockRecorder is the mock recorder for MockImageDeleter.
type MockImageDeleterMockRecorder struct {
	mock *MockImageDeleter
}

// NewMockImageDeleter creates a new mock instance.
func NewMockImageDeleter(ctrl *gomock.Controller) *MockImageDeleter {
	mock := &MockImageDeleter{ctrl: ctrl}
	mock.recorder = &MockImageDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageDeleter) EXPECT() *MockImageDeleterMockRecorder {
	return m.recorder
}

// DeleteImage mocks base method.
func (m *MockImageDeleter) DeleteImage(arg0 imgutil.Image) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteImage", arg0)
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockImageDeleterMockRecorder) DeleteImage(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockImageDeleter)(nil).DeleteImage), arg0)
}

// ImagesEq mocks base method.
func (m *MockImageDeleter) ImagesEq(arg0, arg1 imgutil.Image) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImagesEq", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImagesEq indicates an expected call of ImagesEq.
func (mr *MockImageDeleterMockRecorder) ImagesEq(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImagesEq", reflect.TypeOf((*MockImageDeleter)(nil).ImagesEq), arg0, arg1)
}
