// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/buildpacks/lifecycle (interfaces: MixinValidator)

// Package testmock is a generated GoMock package.
package testmock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	lifecycle "github.com/buildpacks/lifecycle"
	buildpack "github.com/buildpacks/lifecycle/buildpack"
)

// MockMixinValidator is a mock of MixinValidator interface.
type MockMixinValidator struct {
	ctrl     *gomock.Controller
	recorder *MockMixinValidatorMockRecorder
}

// MockMixinValidatorMockRecorder is the mock recorder for MockMixinValidator.
type MockMixinValidatorMockRecorder struct {
	mock *MockMixinValidator
}

// NewMockMixinValidator creates a new mock instance.
func NewMockMixinValidator(ctrl *gomock.Controller) *MockMixinValidator {
	mock := &MockMixinValidator{ctrl: ctrl}
	mock.recorder = &MockMixinValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMixinValidator) EXPECT() *MockMixinValidatorMockRecorder {
	return m.recorder
}

// ValidateMixins mocks base method.
func (m *MockMixinValidator) ValidateMixins(arg0 buildpack.Descriptor, arg1 lifecycle.Analyzed) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateMixins", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateMixins indicates an expected call of ValidateMixins.
func (mr *MockMixinValidatorMockRecorder) ValidateMixins(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateMixins", reflect.TypeOf((*MockMixinValidator)(nil).ValidateMixins), arg0, arg1)
}
