// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/buildpacks/lifecycle (interfaces: LayerSnapshotter)

// Package testmock is a generated GoMock package.
package testmock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLayerSnapshotter is a mock of LayerSnapshotter interface
type MockLayerSnapshotter struct {
	ctrl     *gomock.Controller
	recorder *MockLayerSnapshotterMockRecorder
}

// MockLayerSnapshotterMockRecorder is the mock recorder for MockLayerSnapshotter
type MockLayerSnapshotterMockRecorder struct {
	mock *MockLayerSnapshotter
}

// NewMockLayerSnapshotter creates a new mock instance
func NewMockLayerSnapshotter(ctrl *gomock.Controller) *MockLayerSnapshotter {
	mock := &MockLayerSnapshotter{ctrl: ctrl}
	mock.recorder = &MockLayerSnapshotterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLayerSnapshotter) EXPECT() *MockLayerSnapshotterMockRecorder {
	return m.recorder
}

// ApplySnapshot mocks base method
func (m *MockLayerSnapshotter) ApplySnapshot(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplySnapshot", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplySnapshot indicates an expected call of ApplySnapshot
func (mr *MockLayerSnapshotterMockRecorder) ApplySnapshot(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplySnapshot", reflect.TypeOf((*MockLayerSnapshotter)(nil).ApplySnapshot), arg0)
}

// Init mocks base method
func (m *MockLayerSnapshotter) Init() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init")
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init
func (mr *MockLayerSnapshotterMockRecorder) Init() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockLayerSnapshotter)(nil).Init))
}

// TakeSnapshot mocks base method
func (m *MockLayerSnapshotter) TakeSnapshot(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TakeSnapshot", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// TakeSnapshot indicates an expected call of TakeSnapshot
func (mr *MockLayerSnapshotterMockRecorder) TakeSnapshot(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TakeSnapshot", reflect.TypeOf((*MockLayerSnapshotter)(nil).TakeSnapshot), arg0)
}
