// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/buildpacks/lifecycle/cmd/lifecycle/platform (interfaces: RegistryValidator)

// Package testmock is a generated GoMock package.
package testmock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRegistryValidator is a mock of RegistryValidator interface.
type MockRegistryValidator struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryValidatorMockRecorder
}

// MockRegistryValidatorMockRecorder is the mock recorder for MockRegistryValidator.
type MockRegistryValidatorMockRecorder struct {
	mock *MockRegistryValidator
}

// NewMockRegistryValidator creates a new mock instance.
func NewMockRegistryValidator(ctrl *gomock.Controller) *MockRegistryValidator {
	mock := &MockRegistryValidator{ctrl: ctrl}
	mock.recorder = &MockRegistryValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistryValidator) EXPECT() *MockRegistryValidatorMockRecorder {
	return m.recorder
}

// ReadableRegistryImages mocks base method.
func (m *MockRegistryValidator) ReadableRegistryImages() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadableRegistryImages")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ReadableRegistryImages indicates an expected call of ReadableRegistryImages.
func (mr *MockRegistryValidatorMockRecorder) ReadableRegistryImages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadableRegistryImages", reflect.TypeOf((*MockRegistryValidator)(nil).ReadableRegistryImages))
}

// WriteableRegistryImages mocks base method.
func (m *MockRegistryValidator) WriteableRegistryImages() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteableRegistryImages")
	ret0, _ := ret[0].([]string)
	return ret0
}

// WriteableRegistryImages indicates an expected call of WriteableRegistryImages.
func (mr *MockRegistryValidatorMockRecorder) WriteableRegistryImages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteableRegistryImages", reflect.TypeOf((*MockRegistryValidator)(nil).WriteableRegistryImages))
}
