// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/buildpack/lifecycle/cache (interfaces: ImageFactory)

// Package testmock is a generated GoMock package.
package testmock

import (
	image "github.com/buildpack/lifecycle/image"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockImageFactory is a mock of ImageFactory interface
type MockImageFactory struct {
	ctrl     *gomock.Controller
	recorder *MockImageFactoryMockRecorder
}

// MockImageFactoryMockRecorder is the mock recorder for MockImageFactory
type MockImageFactoryMockRecorder struct {
	mock *MockImageFactory
}

// NewMockImageFactory creates a new mock instance
func NewMockImageFactory(ctrl *gomock.Controller) *MockImageFactory {
	mock := &MockImageFactory{ctrl: ctrl}
	mock.recorder = &MockImageFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockImageFactory) EXPECT() *MockImageFactoryMockRecorder {
	return m.recorder
}

// NewEmptyLocal mocks base method
func (m *MockImageFactory) NewEmptyLocal(arg0 string) image.Image {
	ret := m.ctrl.Call(m, "NewEmptyLocal", arg0)
	ret0, _ := ret[0].(image.Image)
	return ret0
}

// NewEmptyLocal indicates an expected call of NewEmptyLocal
func (mr *MockImageFactoryMockRecorder) NewEmptyLocal(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewEmptyLocal", reflect.TypeOf((*MockImageFactory)(nil).NewEmptyLocal), arg0)
}
