FROM golang:1.17-nanoserver-1809

COPY exec.d/ /go/src/exec.d
WORKDIR /go/src
ENV GO111MODULE=off
RUN go build -o helper.exe exec.d

COPY windows/container /

RUN mkdir c:\layers\0.6_buildpack\some_layer\exec.d\exec.d-checker
RUN copy helper.exe c:\layers\0.6_buildpack\some_layer\exec.d\helper.exe
RUN copy helper.exe c:\layers\0.6_buildpack\some_layer\exec.d\exec.d-checker\helper.exe

ENV PATH="c:\cnb\process;c:\cnb\lifecycle;C:\Windows\system32;C:\Windows;"

ENTRYPOINT ["c:\\cnb\\lifecycle\\launcher"]
